### ISSUE TITLE
rigger 0.5.9 breaks task

### ISSUE THREAD

**Issue by WickyNilliams** [DamonOehlman/grunt-rigger#10]
I've just done a fresh clone of a repo which uses grunt-rigger, and my tasks no longer work. it seems that this is caused by the version of rigger being specified as `0.5.x`, so npm installs rigger `0.5.9` which must contain a breaking/incompatible change?

I've explicitly pegged the rigger version to 0.5.5 in my repo for now, which seems to have fixed it.

**Comment by WickyNilliams** [comment]
Further info: you changed the rigger dependency of underscore to `^1`. underscore just released v1.7 which apparently includes _breaking_ changes. See this tweet https://twitter.com/jdalton/status/504395314191540225

I guess that is where the whole issue originates from!

**Comment by DamonOehlman** [comment]
Thanks for tracking that down - I think underscore thing is going to hurt me in a few places :/

I've just changed and published a new version of rigger that requires `underscore~1.6.0`

**Comment by WickyNilliams** [comment]
i just did a fresh install again and can confirm everything is ok .
