### ISSUE TITLE
Doesn't work on Windows / nodejs 0.8.8

### ISSUE THREAD

**Issue by anodynos** [DamonOehlman/grunt-rigger#2]
grunt-rigger (and actually rigger v.0.2.14) doesn't seem to work on windows (32bit/2003) / nodejs 0.8.8. 

It just produces the original file without the inclusions.

Rigger 0.3.17 works fine, but cant promptly replace v.0.2.14 that grunt-rigger is using... Perhaps you could update to the latest rigger...

**Comment by DamonOehlman** [comment]
Good idea - I'll have a look at doing that in the next day or two.  Just had a quick look then, but I hit a couple of issues installing grunt 0.3.14 with the connect dependency.

**Comment by DamonOehlman** [comment]
@anodynos Well I still can't install grunt (not sure what is going on there), but I've republished grunt-rigger as version 0.3.0 so the minor version numbers line up with rigger.  If you can give it a go and let me know how you get on I'd appreciate it.

**Comment by jamuhl** [comment]
0.3.0 doesn't work - while 0.1.0 is ok (on mac os)

setup is similar to: https://github.com/derickbailey/backbone.marionette/blob/master/grunt.js

**Comment by DamonOehlman** [comment]
@jamuhl Thanks for update - I'll take another look now.

**Comment by DamonOehlman** [comment]
@jamuhl @anodynos Right, found a problem in [rigger](/buildjs/rigger) which I think now yields grunt-rigger@0.3.x ok.  Tested against @derickbailey backbone.marionette and compiled ok.

**Comment by jamuhl** [comment]
@DamonOehlman checked on macos - works like a charm. thx a lot.

**Comment by anodynos** [comment]
@DamonOehlman excellent, it worked liked charm!

tried with http://github.com/derickbailey/backbone.syphon on Windows 2003 x86 + nodejs 0.8.8

Many many thanks!

BTW I am closing the issue...

**Comment by DamonOehlman** [comment]
Great news - if you need any other help or hit other problems feel free to open further issues :)
