### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by tkellen** [DamonOehlman/grunt-rigger#4]
grunt.registerHelper will be depreciated in grunt 0.4.

To see how helpers will be handled in the future (using standard npm require), check out the following links:

https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L15 https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/min.js

PS: join us in #grunt on freenode if you have any questions!

**Comment by DamonOehlman** [comment]
Thanks mate - will take a look.

**Comment by jamuhl** [comment]
done a PR for grunt 0.4.0 support (complete rewrite to match style of grunt-contrib)
#6

**Comment by DamonOehlman** [comment]
@jamuhl All merged and published to npm - thanks again for making this happen.
